const en = {
  heading: "Your reservation details",
  prompt: "Enter the email used for your booking. We will send you a secure link to reopen your confirmation.",
  email: "Booking email", button: "Email my secure link",
  sent: "If the email matches this reservation, a secure link will arrive shortly. Check your spam folder too.",
  failed: "Please wait a moment and try again.",
  subject: "Your secure reservation link — Portugal Active",
  body: "You requested a new link to your reservation. Open your confirmation below. If you did not request this email, you can ignore it.",
  open: "View my reservation",
};
export const RECEIPT_ACCESS_COPY: Record<string, typeof en> = {
  en,
  pt: { heading: "Os detalhes da sua reserva", prompt: "Introduza o email usado na reserva. Enviaremos um link seguro para voltar a abrir a confirmação.", email: "Email da reserva", button: "Receber link seguro", sent: "Se o email corresponder a esta reserva, receberá um link seguro em breve. Verifique também a pasta de spam.", failed: "Aguarde um momento e tente novamente.", subject: "O seu link seguro para a reserva — Portugal Active", body: "Pediu um novo link para a sua reserva. Abra a confirmação abaixo. Se não fez este pedido, pode ignorar este email.", open: "Ver a minha reserva" },
  es: { heading: "Los detalles de su reserva", prompt: "Introduzca el correo usado para reservar. Le enviaremos un enlace seguro para volver a abrir la confirmación.", email: "Correo de la reserva", button: "Recibir enlace seguro", sent: "Si el correo coincide con esta reserva, recibirá un enlace seguro en breve. Revise también la carpeta de spam.", failed: "Espere un momento e inténtelo de nuevo.", subject: "Su enlace seguro de reserva — Portugal Active", body: "Ha solicitado un nuevo enlace para su reserva. Abra la confirmación a continuación. Si no lo ha solicitado, puede ignorar este correo.", open: "Ver mi reserva" },
  fr: { heading: "Les détails de votre réservation", prompt: "Saisissez l’adresse e-mail utilisée pour réserver. Nous vous enverrons un lien sécurisé pour rouvrir votre confirmation.", email: "E-mail de réservation", button: "Recevoir mon lien sécurisé", sent: "Si l’adresse correspond à cette réservation, vous recevrez bientôt un lien sécurisé. Vérifiez aussi vos courriers indésirables.", failed: "Patientez un instant et réessayez.", subject: "Votre lien de réservation sécurisé — Portugal Active", body: "Vous avez demandé un nouveau lien vers votre réservation. Ouvrez votre confirmation ci-dessous. Si vous n’avez pas fait cette demande, ignorez cet e-mail.", open: "Voir ma réservation" },
  de: { heading: "Ihre Buchungsdetails", prompt: "Geben Sie die bei der Buchung verwendete E-Mail-Adresse ein. Wir senden Ihnen einen sicheren Link zu Ihrer Bestätigung.", email: "E-Mail-Adresse der Buchung", button: "Sicheren Link erhalten", sent: "Wenn die Adresse zu dieser Buchung gehört, erhalten Sie in Kürze einen sicheren Link. Prüfen Sie auch Ihren Spam-Ordner.", failed: "Bitte warten Sie kurz und versuchen Sie es erneut.", subject: "Ihr sicherer Buchungslink — Portugal Active", body: "Sie haben einen neuen Link zu Ihrer Buchung angefordert. Öffnen Sie unten Ihre Bestätigung. Falls Sie diese Anfrage nicht gestellt haben, können Sie diese E-Mail ignorieren.", open: "Meine Buchung ansehen" },
  it: { heading: "I dettagli della prenotazione", prompt: "Inserisci l’email usata per prenotare. Ti invieremo un link sicuro per riaprire la conferma.", email: "Email della prenotazione", button: "Ricevi il link sicuro", sent: "Se l’email corrisponde a questa prenotazione, riceverai presto un link sicuro. Controlla anche la cartella spam.", failed: "Attendi un momento e riprova.", subject: "Il tuo link sicuro alla prenotazione — Portugal Active", body: "Hai richiesto un nuovo link alla tua prenotazione. Apri la conferma qui sotto. Se non hai fatto questa richiesta, puoi ignorare questa email.", open: "Vedi la mia prenotazione" },
  nl: { heading: "Uw reserveringsgegevens", prompt: "Vul het e-mailadres van uw boeking in. We sturen u een veilige link om uw bevestiging opnieuw te openen.", email: "E-mailadres van de boeking", button: "Veilige link ontvangen", sent: "Als het adres bij deze reservering hoort, ontvangt u binnenkort een veilige link. Controleer ook uw spammap.", failed: "Wacht even en probeer het opnieuw.", subject: "Uw veilige reserveringslink — Portugal Active", body: "U heeft een nieuwe link naar uw reservering aangevraagd. Open hieronder uw bevestiging. Als u dit niet heeft aangevraagd, kunt u deze e-mail negeren.", open: "Mijn reservering bekijken" },
  fi: { heading: "Varauksesi tiedot", prompt: "Anna varauksessa käyttämäsi sähköpostiosoite. Lähetämme turvallisen linkin varausvahvistuksen avaamiseen.", email: "Varauksen sähköpostiosoite", button: "Lähetä turvallinen linkki", sent: "Jos osoite vastaa tätä varausta, saat pian turvallisen linkin. Tarkista myös roskapostikansio.", failed: "Odota hetki ja yritä uudelleen.", subject: "Turvallinen linkki varaukseesi — Portugal Active", body: "Pyysit uutta linkkiä varaukseesi. Avaa vahvistus alta. Jos et tehnyt tätä pyyntöä, voit jättää tämän viestin huomiotta.", open: "Näytä varaukseni" },
  sv: { heading: "Dina bokningsuppgifter", prompt: "Ange e-postadressen som användes vid bokningen. Vi skickar en säker länk för att öppna din bekräftelse igen.", email: "Bokningens e-postadress", button: "Få en säker länk", sent: "Om adressen stämmer med bokningen får du snart en säker länk. Kontrollera även skräppostmappen.", failed: "Vänta en stund och försök igen.", subject: "Din säkra bokningslänk — Portugal Active", body: "Du har begärt en ny länk till din bokning. Öppna bekräftelsen nedan. Om du inte har gjort denna begäran kan du ignorera detta mejl.", open: "Visa min bokning" },
};
export function receiptAccessCopy(locale?: string | null) {
  return RECEIPT_ACCESS_COPY[(locale || "en").slice(0, 2).toLowerCase()] || en;
}
