/**
 * Copy do funil de recuperação (4 contactos), nas 9 línguas do site.
 * Regras (./email-i18n.ts): o Flex nunca se chama seguro em nenhuma língua
 * (insurance, assurance, seguro, assicurazione, Versicherung, verzekering,
 * försäkring, vakuutus); promete-se o preço, nunca as datas; sem travessão a
 * fazer de vírgula. As strings partilhadas (saudação, rótulos, CTA de retoma,
 * WhatsApp, opt-out) continuam em RECOVERY_I18N.
 */
import type { EmailLang } from "./email-i18n";

export interface FunnelStrings {
  // 1 · a casa
  subject1: (h: string) => string;
  preheader1: string;
  headline1: string;
  body1: (g: string, h: string) => string;
  personal1: string;
  // 1 · variante: parou no pagamento
  subject1Pay: (h: string) => string;
  preheader1Pay: string;
  headline1Pay: string;
  body1Pay: (g: string, h: string) => string;
  personal1Pay: string;
  // 2 · urgência verdadeira
  subject2: (h: string, time: string) => string;
  preheader2: string;
  headline2: string;
  body2: (g: string, h: string, until: string) => string;
  scarcity: (unavailable: number, total: number) => string;
  // 3 · datas livres + Flex oferecido
  subject3: (h: string) => string;
  preheader3Gift: string;
  preheader3: string;
  headline3: string;
  body3: (g: string, h: string) => string;
  giftTitle: string;
  giftBody: (until: string, days: number, value: string) => string;
  cta3Gift: string;
  cta3: string;
  flexIncluded: string;
  // 4 · alternativas (último)
  subject4: (h: string) => string;
  subject4None: (h: string) => string;
  preheader4: string;
  headline4: string;
  body4: (g: string, h: string) => string;
  body4None: (g: string, h: string) => string;
  ownLink: (h: string) => string;
  lastNote: string;
}

export const FUNNEL_I18N: Record<EmailLang, FunnelStrings> = {
  pt: {
    subject1: (h) => `${h} continua à sua espera`,
    preheader1: "As datas, os hóspedes e o preço que viu ficaram guardados.",
    headline1: "A sua casa continua à sua espera.",
    body1: (g, h) => `${g} guardámos a sua estadia em ${h} exatamente como a deixou: as datas, os hóspedes e o preço. Basta um clique para continuar, neste ou noutro dispositivo.`,
    personal1: "Se quiser saber mais sobre a casa ou a região antes de decidir, responda a este email. Lemos todas as respostas.",
    subject1Pay: (h) => `A sua reserva em ${h} ficou a meio`,
    preheader1Pay: "O preço mantém-se. Pode concluir com cartão, Apple Pay, Google Pay, PayPal ou Klarna.",
    headline1Pay: "Ficou algo por resolver?",
    body1Pay: (g, h) => `${g} chegou ao pagamento da sua estadia em ${h}, mas a reserva não ficou concluída. Acontece a muitos hóspedes: um cartão recusado, um limite do banco, uma dúvida de última hora. O seu preço mantém-se e pode pagar como preferir: cartão, Apple Pay ou Google Pay, PayPal, ou dividir o pagamento com Klarna.`,
    personal1Pay: "Prefere tratar disto com uma pessoa? Responda a este email ou escreva-nos por WhatsApp e concluímos a reserva consigo.",
    subject2: (h, t) => `${h}: o seu preço mantém-se até às ${t}`,
    preheader2: "Depois dessa hora o valor é recalculado para as suas datas.",
    headline2: "O seu preço mantém-se por mais algumas horas.",
    body2: (g, h, u) => `${g} o preço que viu para ${h} está garantido até ${u}. Depois disso voltamos a calcular o valor, e as datas continuam abertas a outros hóspedes até alguém reservar.`,
    scarcity: (u, t) => `Das ${t} noites à volta das suas datas, ${u} já não estão disponíveis.`,
    subject3: (h) => `As suas datas em ${h} continuam livres`,
    preheader3Gift: "Atualizámos o preço e o Flex fica por nossa conta durante 72 horas.",
    preheader3: "Voltámos a verificar a disponibilidade e atualizámos o preço.",
    headline3: "As suas datas continuam livres.",
    body3: (g, h) => `${g} voltámos a verificar ${h} para as suas datas e continuam disponíveis. Atualizámos o preço para hoje: é o valor que vê abaixo.`,
    giftTitle: "O Flex fica por nossa conta",
    giftBody: (u, d, v) => `Reserve até ${u} e oferecemos o Flex, que normalmente custa ${v}. Se os seus planos mudarem, pode remarcar a estadia até ${d} dias antes do check-in sem perder o valor pago.`,
    cta3Gift: "Reservar com o Flex oferecido",
    cta3: "Ver o preço de hoje",
    flexIncluded: "Flex oferecido",
    subject4: (h) => `Se ${h} não é bem a casa certa`,
    subject4None: () => "Continuamos a ajudar com a sua estadia",
    preheader4: "Casas na mesma região, livres nas mesmas datas.",
    headline4: "Talvez a casa certa seja outra.",
    body4: (g, h) => `${g} ainda não reservou ${h}, e está tudo bem: escolher a casa certa leva tempo. Escolhemos casas na mesma região, livres nas suas datas, que achamos que lhe vão agradar.`,
    body4None: (g, h) => `${g} ainda não reservou ${h}. Se as datas ou a casa não encaixam no que procura, diga-nos o que tem em mente e o nosso concierge encontra a opção certa para si.`,
    ownLink: (h) => `Voltar a ${h}`,
    lastNote: "Este é o último email que lhe enviamos sobre esta reserva.",
  },
  en: {
    subject1: (h) => `${h} is still waiting for you`,
    preheader1: "Your dates, guests and the price you saw are saved.",
    headline1: "Your home is still waiting for you.",
    body1: (g, h) => `${g} we saved your stay at ${h} exactly as you left it: the dates, the guests and the price. One click and you're back, on this device or any other.`,
    personal1: "If you'd like to know more about the house or the area before deciding, just reply to this email. We read every reply.",
    subject1Pay: (h) => `Your booking at ${h} is halfway there`,
    preheader1Pay: "Your price still stands. Finish with card, Apple Pay, Google Pay, PayPal or Klarna.",
    headline1Pay: "Did something get in the way?",
    body1Pay: (g, h) => `${g} you reached the payment step for your stay at ${h}, but the booking wasn't completed. It happens to many guests: a declined card, a bank limit, a last-minute question. Your price still stands and you can pay however suits you: card, Apple Pay or Google Pay, PayPal, or split the payment with Klarna.`,
    personal1Pay: "Would you rather sort this out with a person? Reply to this email or message us on WhatsApp and we'll complete the booking with you.",
    subject2: (h, t) => `${h}: your price holds until ${t}`,
    preheader2: "After that, the rate for your dates is recalculated.",
    headline2: "Your price holds for a few more hours.",
    body2: (g, h, u) => `${g} the price you saw for ${h} is guaranteed until ${u}. After that we recalculate the rate, and the dates stay open to other guests until someone books.`,
    scarcity: (u, t) => `Of the ${t} nights around your dates, ${u} are no longer available.`,
    subject3: (h) => `Your dates at ${h} are still free`,
    preheader3Gift: "We've updated the price, and Flex is on us for the next 72 hours.",
    preheader3: "We rechecked availability and updated the price.",
    headline3: "Your dates are still free.",
    body3: (g, h) => `${g} we checked ${h} again for your dates and they're still available. We've updated the price to today's rate, shown below.`,
    giftTitle: "Flex is on us",
    giftBody: (u, d, v) => `Book by ${u} and we'll include Flex, normally ${v}. If your plans change, you can move your stay up to ${d} days before check-in without losing what you paid.`,
    cta3Gift: "Book with Flex included",
    cta3: "See today's price",
    flexIncluded: "Flex included",
    subject4: (h) => `If ${h} isn't quite right`,
    subject4None: () => "We're still here to help with your stay",
    preheader4: "Homes in the same region, free on the same dates.",
    headline4: "Perhaps the right home is another one.",
    body4: (g, h) => `${g} you haven't booked ${h} yet, and that's fine: finding the right home takes time. We picked homes in the same region, free on your dates, that we think you'll love.`,
    body4None: (g, h) => `${g} you haven't booked ${h} yet. If the dates or the house aren't quite what you're after, tell us what you have in mind and our concierge will find the right option for you.`,
    ownLink: (h) => `Back to ${h}`,
    lastNote: "This is the last email we'll send you about this booking.",
  },
  fr: {
    subject1: (h) => `${h} vous attend toujours`,
    preheader1: "Vos dates, vos voyageurs et le prix affiché sont conservés.",
    headline1: "Votre maison vous attend toujours.",
    body1: (g, h) => `${g} nous avons conservé votre séjour à ${h} exactement tel que vous l'avez laissé : les dates, les voyageurs et le prix. Un clic suffit pour reprendre, sur cet appareil ou un autre.`,
    personal1: "Si vous souhaitez en savoir plus sur la maison ou la région avant de décider, répondez simplement à cet email. Nous lisons toutes les réponses.",
    subject1Pay: (h) => `Votre réservation à ${h} est restée en suspens`,
    preheader1Pay: "Votre prix est maintenu. Finalisez par carte, Apple Pay, Google Pay, PayPal ou Klarna.",
    headline1Pay: "Un imprévu au moment de payer ?",
    body1Pay: (g, h) => `${g} vous êtes arrivé au paiement de votre séjour à ${h}, mais la réservation n'a pas été finalisée. Cela arrive souvent : une carte refusée, un plafond bancaire, une question de dernière minute. Votre prix est maintenu et vous pouvez payer comme vous le souhaitez : carte, Apple Pay ou Google Pay, PayPal, ou en plusieurs fois avec Klarna.`,
    personal1Pay: "Vous préférez régler cela avec une personne ? Répondez à cet email ou écrivez-nous sur WhatsApp et nous finaliserons la réservation avec vous.",
    subject2: (h, t) => `${h} : votre prix est maintenu jusqu'à ${t}`,
    preheader2: "Passé ce délai, le tarif de vos dates est recalculé.",
    headline2: "Votre prix est maintenu encore quelques heures.",
    body2: (g, h, u) => `${g} le prix affiché pour ${h} est garanti jusqu'au ${u}. Ensuite, nous recalculons le tarif, et les dates restent ouvertes aux autres voyageurs jusqu'à ce que quelqu'un réserve.`,
    scarcity: (u, t) => `Sur les ${t} nuits autour de vos dates, ${u} ne sont plus disponibles.`,
    subject3: (h) => `Vos dates à ${h} sont toujours libres`,
    preheader3Gift: "Nous avons mis à jour le prix, et Flex vous est offert pendant 72 heures.",
    preheader3: "Nous avons revérifié la disponibilité et mis à jour le prix.",
    headline3: "Vos dates sont toujours libres.",
    body3: (g, h) => `${g} nous avons revérifié ${h} pour vos dates et elles sont toujours disponibles. Nous avons mis à jour le prix au tarif du jour, indiqué ci-dessous.`,
    giftTitle: "Flex vous est offert",
    giftBody: (u, d, v) => `Réservez avant le ${u} et nous vous offrons Flex, habituellement à ${v}. Si vos projets changent, vous pouvez reporter votre séjour jusqu'à ${d} jours avant l'arrivée sans perdre le montant payé.`,
    cta3Gift: "Réserver avec Flex offert",
    cta3: "Voir le prix du jour",
    flexIncluded: "Flex offert",
    subject4: (h) => `Si ${h} n'est pas tout à fait la bonne`,
    subject4None: () => "Nous restons à vos côtés pour votre séjour",
    preheader4: "Des maisons dans la même région, libres aux mêmes dates.",
    headline4: "La bonne maison est peut-être une autre.",
    body4: (g, h) => `${g} vous n'avez pas encore réservé ${h}, et c'est normal : trouver la bonne maison prend du temps. Nous avons choisi des maisons dans la même région, libres à vos dates, qui devraient vous plaire.`,
    body4None: (g, h) => `${g} vous n'avez pas encore réservé ${h}. Si les dates ou la maison ne correspondent pas tout à fait, dites-nous ce que vous cherchez et notre concierge trouvera l'option idéale.`,
    ownLink: (h) => `Revenir à ${h}`,
    lastNote: "C'est le dernier email que nous vous envoyons au sujet de cette réservation.",
  },
  es: {
    subject1: (h) => `${h} sigue esperándole`,
    preheader1: "Sus fechas, huéspedes y el precio que vio están guardados.",
    headline1: "Su casa sigue esperándole.",
    body1: (g, h) => `${g} guardamos su estancia en ${h} tal como la dejó: las fechas, los huéspedes y el precio. Un clic y puede continuar, en este dispositivo o en otro.`,
    personal1: "Si quiere saber más sobre la casa o la zona antes de decidir, responda a este email. Leemos todas las respuestas.",
    subject1Pay: (h) => `Su reserva en ${h} quedó a medias`,
    preheader1Pay: "Su precio se mantiene. Termine con tarjeta, Apple Pay, Google Pay, PayPal o Klarna.",
    headline1Pay: "¿Algo se interpuso?",
    body1Pay: (g, h) => `${g} llegó al pago de su estancia en ${h}, pero la reserva no se completó. Le pasa a muchos huéspedes: una tarjeta rechazada, un límite del banco, una duda de última hora. Su precio se mantiene y puede pagar como prefiera: tarjeta, Apple Pay o Google Pay, PayPal, o dividir el pago con Klarna.`,
    personal1Pay: "¿Prefiere resolverlo con una persona? Responda a este email o escríbanos por WhatsApp y completamos la reserva con usted.",
    subject2: (h, t) => `${h}: su precio se mantiene hasta las ${t}`,
    preheader2: "Después, el precio de sus fechas se recalcula.",
    headline2: "Su precio se mantiene unas horas más.",
    body2: (g, h, u) => `${g} el precio que vio para ${h} está garantizado hasta el ${u}. Después recalculamos la tarifa, y las fechas siguen abiertas a otros huéspedes hasta que alguien reserve.`,
    scarcity: (u, t) => `De las ${t} noches alrededor de sus fechas, ${u} ya no están disponibles.`,
    subject3: (h) => `Sus fechas en ${h} siguen libres`,
    preheader3Gift: "Hemos actualizado el precio y Flex corre de nuestra cuenta durante 72 horas.",
    preheader3: "Hemos vuelto a comprobar la disponibilidad y actualizado el precio.",
    headline3: "Sus fechas siguen libres.",
    body3: (g, h) => `${g} hemos vuelto a comprobar ${h} para sus fechas y siguen disponibles. Hemos actualizado el precio a la tarifa de hoy, que ve a continuación.`,
    giftTitle: "Flex corre de nuestra cuenta",
    giftBody: (u, d, v) => `Reserve antes del ${u} y le regalamos Flex, que normalmente cuesta ${v}. Si sus planes cambian, puede cambiar la fecha de su estancia hasta ${d} días antes del check-in sin perder lo pagado.`,
    cta3Gift: "Reservar con Flex incluido",
    cta3: "Ver el precio de hoy",
    flexIncluded: "Flex incluido",
    subject4: (h) => `Si ${h} no es del todo la casa`,
    subject4None: () => "Seguimos ayudándole con su estancia",
    preheader4: "Casas en la misma región, libres en las mismas fechas.",
    headline4: "Quizá la casa ideal sea otra.",
    body4: (g, h) => `${g} aún no ha reservado ${h}, y no pasa nada: elegir la casa adecuada lleva tiempo. Hemos elegido casas en la misma región, libres en sus fechas, que creemos que le encantarán.`,
    body4None: (g, h) => `${g} aún no ha reservado ${h}. Si las fechas o la casa no encajan con lo que busca, cuéntenos qué tiene en mente y nuestro concierge encontrará la opción adecuada.`,
    ownLink: (h) => `Volver a ${h}`,
    lastNote: "Este es el último email que le enviamos sobre esta reserva.",
  },
  it: {
    subject1: (h) => `${h} ti sta ancora aspettando`,
    preheader1: "Date, ospiti e il prezzo che hai visto sono salvati.",
    headline1: "La tua casa ti sta ancora aspettando.",
    body1: (g, h) => `${g} abbiamo salvato il tuo soggiorno a ${h} esattamente come l'hai lasciato: date, ospiti e prezzo. Basta un clic per continuare, su questo dispositivo o su un altro.`,
    personal1: "Se vuoi saperne di più sulla casa o sulla zona prima di decidere, rispondi a questa email. Leggiamo tutte le risposte.",
    subject1Pay: (h) => `La tua prenotazione a ${h} è rimasta a metà`,
    preheader1Pay: "Il prezzo resta valido. Completa con carta, Apple Pay, Google Pay, PayPal o Klarna.",
    headline1Pay: "Qualcosa è andato storto?",
    body1Pay: (g, h) => `${g} sei arrivato al pagamento del soggiorno a ${h}, ma la prenotazione non è stata completata. Capita a molti ospiti: una carta rifiutata, un limite della banca, un dubbio dell'ultimo minuto. Il prezzo resta valido e puoi pagare come preferisci: carta, Apple Pay o Google Pay, PayPal, oppure dividere il pagamento con Klarna.`,
    personal1Pay: "Preferisci risolvere con una persona? Rispondi a questa email o scrivici su WhatsApp e completiamo la prenotazione insieme.",
    subject2: (h, t) => `${h}: il tuo prezzo resta valido fino alle ${t}`,
    preheader2: "Dopo, il prezzo per le tue date viene ricalcolato.",
    headline2: "Il tuo prezzo resta valido ancora per qualche ora.",
    body2: (g, h, u) => `${g} il prezzo che hai visto per ${h} è garantito fino a ${u}. Poi ricalcoliamo la tariffa, e le date restano aperte ad altri ospiti finché qualcuno non prenota.`,
    scarcity: (u, t) => `Delle ${t} notti intorno alle tue date, ${u} non sono più disponibili.`,
    subject3: (h) => `Le tue date a ${h} sono ancora libere`,
    preheader3Gift: "Abbiamo aggiornato il prezzo e Flex te lo offriamo noi per 72 ore.",
    preheader3: "Abbiamo ricontrollato la disponibilità e aggiornato il prezzo.",
    headline3: "Le tue date sono ancora libere.",
    body3: (g, h) => `${g} abbiamo ricontrollato ${h} per le tue date e sono ancora disponibili. Abbiamo aggiornato il prezzo alla tariffa di oggi, indicata qui sotto.`,
    giftTitle: "Flex te lo offriamo noi",
    giftBody: (u, d, v) => `Prenota entro ${u} e ti offriamo Flex, che normalmente costa ${v}. Se i tuoi piani cambiano, puoi spostare il soggiorno fino a ${d} giorni prima del check-in senza perdere quanto pagato.`,
    cta3Gift: "Prenota con Flex incluso",
    cta3: "Vedi il prezzo di oggi",
    flexIncluded: "Flex incluso",
    subject4: (h) => `Se ${h} non è proprio la casa giusta`,
    subject4None: () => "Siamo ancora qui per il tuo soggiorno",
    preheader4: "Case nella stessa zona, libere nelle stesse date.",
    headline4: "Forse la casa giusta è un'altra.",
    body4: (g, h) => `${g} non hai ancora prenotato ${h}, ed è normale: scegliere la casa giusta richiede tempo. Abbiamo scelto case nella stessa zona, libere nelle tue date, che pensiamo ti piaceranno.`,
    body4None: (g, h) => `${g} non hai ancora prenotato ${h}. Se le date o la casa non sono quello che cerchi, dicci cosa hai in mente e il nostro concierge troverà l'opzione giusta per te.`,
    ownLink: (h) => `Torna a ${h}`,
    lastNote: "Questa è l'ultima email che ti inviamo su questa prenotazione.",
  },
  de: {
    subject1: (h) => `${h} wartet noch auf Sie`,
    preheader1: "Ihre Daten, Gäste und der angezeigte Preis sind gespeichert.",
    headline1: "Ihr Haus wartet noch auf Sie.",
    body1: (g, h) => `${g} wir haben Ihren Aufenthalt in ${h} genau so gespeichert, wie Sie ihn verlassen haben: Daten, Gäste und Preis. Ein Klick genügt, um weiterzumachen, auf diesem oder einem anderen Gerät.`,
    personal1: "Wenn Sie vor Ihrer Entscheidung mehr über das Haus oder die Region wissen möchten, antworten Sie einfach auf diese E-Mail. Wir lesen jede Antwort.",
    subject1Pay: (h) => `Ihre Buchung für ${h} ist noch offen`,
    preheader1Pay: "Ihr Preis gilt weiterhin. Abschließen per Karte, Apple Pay, Google Pay, PayPal oder Klarna.",
    headline1Pay: "Ist etwas dazwischengekommen?",
    body1Pay: (g, h) => `${g} Sie waren bereits bei der Zahlung für Ihren Aufenthalt in ${h}, aber die Buchung wurde nicht abgeschlossen. Das passiert vielen Gästen: eine abgelehnte Karte, ein Banklimit, eine Frage in letzter Minute. Ihr Preis gilt weiterhin und Sie können bezahlen, wie es Ihnen passt: Karte, Apple Pay oder Google Pay, PayPal oder in Raten mit Klarna.`,
    personal1Pay: "Möchten Sie das lieber mit einem Menschen klären? Antworten Sie auf diese E-Mail oder schreiben Sie uns auf WhatsApp, und wir schließen die Buchung gemeinsam ab.",
    subject2: (h, t) => `${h}: Ihr Preis gilt bis ${t} Uhr`,
    preheader2: "Danach wird der Preis für Ihre Daten neu berechnet.",
    headline2: "Ihr Preis gilt noch einige Stunden.",
    body2: (g, h, u) => `${g} der angezeigte Preis für ${h} ist bis ${u} garantiert. Danach berechnen wir den Preis neu, und die Daten bleiben für andere Gäste buchbar, bis jemand bucht.`,
    scarcity: (u, t) => `Von den ${t} Nächten rund um Ihre Daten sind ${u} bereits nicht mehr verfügbar.`,
    subject3: (h) => `Ihre Daten in ${h} sind noch frei`,
    preheader3Gift: "Wir haben den Preis aktualisiert, und Flex geht 72 Stunden lang auf uns.",
    preheader3: "Wir haben die Verfügbarkeit erneut geprüft und den Preis aktualisiert.",
    headline3: "Ihre Daten sind noch frei.",
    body3: (g, h) => `${g} wir haben ${h} für Ihre Daten erneut geprüft, und sie sind noch verfügbar. Den Preis haben wir auf den heutigen Tarif aktualisiert, siehe unten.`,
    giftTitle: "Flex geht auf uns",
    giftBody: (u, d, v) => `Buchen Sie bis ${u}, und wir schenken Ihnen Flex, das normalerweise ${v} kostet. Wenn sich Ihre Pläne ändern, können Sie Ihren Aufenthalt bis ${d} Tage vor der Anreise umbuchen, ohne den bezahlten Betrag zu verlieren.`,
    cta3Gift: "Mit Flex inklusive buchen",
    cta3: "Heutigen Preis ansehen",
    flexIncluded: "Flex inklusive",
    subject4: (h) => `Falls ${h} nicht ganz das Richtige ist`,
    subject4None: () => "Wir helfen Ihnen weiterhin bei Ihrem Aufenthalt",
    preheader4: "Häuser in derselben Region, frei zu denselben Daten.",
    headline4: "Vielleicht ist das richtige Haus ein anderes.",
    body4: (g, h) => `${g} Sie haben ${h} noch nicht gebucht, und das ist in Ordnung: Das richtige Haus zu finden braucht Zeit. Wir haben Häuser in derselben Region ausgewählt, die zu Ihren Daten frei sind und Ihnen gefallen dürften.`,
    body4None: (g, h) => `${g} Sie haben ${h} noch nicht gebucht. Wenn Daten oder Haus nicht ganz passen, sagen Sie uns, was Sie suchen, und unser Concierge findet die richtige Option für Sie.`,
    ownLink: (h) => `Zurück zu ${h}`,
    lastNote: "Dies ist die letzte E-Mail, die wir Ihnen zu dieser Buchung senden.",
  },
  nl: {
    subject1: (h) => `${h} wacht nog op u`,
    preheader1: "Uw data, gasten en de getoonde prijs zijn bewaard.",
    headline1: "Uw huis wacht nog op u.",
    body1: (g, h) => `${g} we hebben uw verblijf in ${h} precies zo bewaard als u het achterliet: de data, de gasten en de prijs. Eén klik en u gaat verder, op dit of een ander apparaat.`,
    personal1: "Wilt u voor uw beslissing meer weten over het huis of de streek? Beantwoord dan deze e-mail. We lezen elk antwoord.",
    subject1Pay: (h) => `Uw boeking voor ${h} staat nog open`,
    preheader1Pay: "Uw prijs blijft staan. Rond af met kaart, Apple Pay, Google Pay, PayPal of Klarna.",
    headline1Pay: "Kwam er iets tussen?",
    body1Pay: (g, h) => `${g} u was al bij de betaling voor uw verblijf in ${h}, maar de boeking is niet afgerond. Dat overkomt veel gasten: een geweigerde kaart, een banklimiet, een vraag op het laatste moment. Uw prijs blijft staan en u betaalt zoals u wilt: kaart, Apple Pay of Google Pay, PayPal, of gespreid met Klarna.`,
    personal1Pay: "Regelt u dit liever met een persoon? Beantwoord deze e-mail of stuur ons een bericht via WhatsApp en we ronden de boeking samen af.",
    subject2: (h, t) => `${h}: uw prijs geldt tot ${t}`,
    preheader2: "Daarna wordt de prijs voor uw data opnieuw berekend.",
    headline2: "Uw prijs geldt nog enkele uren.",
    body2: (g, h, u) => `${g} de prijs die u zag voor ${h} is gegarandeerd tot ${u}. Daarna berekenen we de prijs opnieuw, en blijven de data open voor andere gasten tot iemand boekt.`,
    scarcity: (u, t) => `Van de ${t} nachten rond uw data zijn er ${u} al niet meer beschikbaar.`,
    subject3: (h) => `Uw data in ${h} zijn nog vrij`,
    preheader3Gift: "We hebben de prijs bijgewerkt, en Flex is 72 uur lang van ons.",
    preheader3: "We hebben de beschikbaarheid opnieuw gecontroleerd en de prijs bijgewerkt.",
    headline3: "Uw data zijn nog vrij.",
    body3: (g, h) => `${g} we hebben ${h} opnieuw gecontroleerd voor uw data en ze zijn nog beschikbaar. We hebben de prijs bijgewerkt naar het tarief van vandaag, hieronder.`,
    giftTitle: "Flex is van ons",
    giftBody: (u, d, v) => `Boek vóór ${u} en we bieden u Flex aan, normaal ${v}. Veranderen uw plannen, dan kunt u uw verblijf tot ${d} dagen voor aankomst verzetten zonder het betaalde bedrag te verliezen.`,
    cta3Gift: "Boeken met Flex inbegrepen",
    cta3: "Bekijk de prijs van vandaag",
    flexIncluded: "Flex inbegrepen",
    subject4: (h) => `Als ${h} niet helemaal het juiste huis is`,
    subject4None: () => "We helpen u graag verder met uw verblijf",
    preheader4: "Huizen in dezelfde streek, vrij op dezelfde data.",
    headline4: "Misschien is het juiste huis een ander.",
    body4: (g, h) => `${g} u heeft ${h} nog niet geboekt, en dat is prima: het juiste huis vinden kost tijd. We kozen huizen in dezelfde streek, vrij op uw data, waarvan we denken dat u ze mooi vindt.`,
    body4None: (g, h) => `${g} u heeft ${h} nog niet geboekt. Passen de data of het huis niet helemaal? Vertel ons wat u zoekt en onze concierge vindt de juiste optie voor u.`,
    ownLink: (h) => `Terug naar ${h}`,
    lastNote: "Dit is de laatste e-mail die we u over deze boeking sturen.",
  },
  sv: {
    subject1: (h) => `${h} väntar fortfarande på dig`,
    preheader1: "Dina datum, gäster och priset du såg är sparade.",
    headline1: "Ditt hem väntar fortfarande på dig.",
    body1: (g, h) => `${g} vi har sparat din vistelse på ${h} precis som du lämnade den: datum, gäster och pris. Ett klick så fortsätter du, på den här enheten eller en annan.`,
    personal1: "Vill du veta mer om huset eller området innan du bestämmer dig? Svara bara på det här mejlet. Vi läser varje svar.",
    subject1Pay: (h) => `Din bokning av ${h} blev inte klar`,
    preheader1Pay: "Ditt pris gäller fortfarande. Slutför med kort, Apple Pay, Google Pay, PayPal eller Klarna.",
    headline1Pay: "Kom något emellan?",
    body1Pay: (g, h) => `${g} du kom till betalningen för din vistelse på ${h}, men bokningen slutfördes inte. Det händer många gäster: ett nekat kort, en bankgräns, en fråga i sista stund. Ditt pris gäller fortfarande och du kan betala som du vill: kort, Apple Pay eller Google Pay, PayPal, eller dela upp betalningen med Klarna.`,
    personal1Pay: "Vill du hellre lösa det med en person? Svara på det här mejlet eller skriv till oss på WhatsApp så slutför vi bokningen tillsammans.",
    subject2: (h, t) => `${h}: ditt pris gäller till ${t}`,
    preheader2: "Därefter räknas priset för dina datum om.",
    headline2: "Ditt pris gäller några timmar till.",
    body2: (g, h, u) => `${g} priset du såg för ${h} är garanterat till ${u}. Därefter räknar vi om priset, och datumen är öppna för andra gäster tills någon bokar.`,
    scarcity: (u, t) => `Av de ${t} nätterna runt dina datum är ${u} inte längre tillgängliga.`,
    subject3: (h) => `Dina datum på ${h} är fortfarande lediga`,
    preheader3Gift: "Vi har uppdaterat priset, och Flex bjuder vi på i 72 timmar.",
    preheader3: "Vi har kontrollerat tillgängligheten igen och uppdaterat priset.",
    headline3: "Dina datum är fortfarande lediga.",
    body3: (g, h) => `${g} vi har kontrollerat ${h} igen för dina datum och de är fortfarande lediga. Vi har uppdaterat priset till dagens pris, se nedan.`,
    giftTitle: "Flex bjuder vi på",
    giftBody: (u, d, v) => `Boka senast ${u} så bjuder vi på Flex, som normalt kostar ${v}. Om dina planer ändras kan du flytta vistelsen upp till ${d} dagar före ankomst utan att förlora det du betalat.`,
    cta3Gift: "Boka med Flex inkluderat",
    cta3: "Se dagens pris",
    flexIncluded: "Flex inkluderat",
    subject4: (h) => `Om ${h} inte riktigt är rätt hem`,
    subject4None: () => "Vi hjälper dig gärna vidare med din vistelse",
    preheader4: "Hem i samma region, lediga samma datum.",
    headline4: "Kanske är rätt hem ett annat.",
    body4: (g, h) => `${g} du har inte bokat ${h} än, och det är helt okej: att hitta rätt hem tar tid. Vi har valt hem i samma region, lediga dina datum, som vi tror att du kommer att gilla.`,
    body4None: (g, h) => `${g} du har inte bokat ${h} än. Om datumen eller huset inte riktigt passar, berätta vad du söker så hittar vår concierge rätt alternativ åt dig.`,
    ownLink: (h) => `Tillbaka till ${h}`,
    lastNote: "Det här är det sista mejlet vi skickar om den här bokningen.",
  },
  fi: {
    subject1: (h) => `${h} odottaa yhä sinua`,
    preheader1: "Päivämäärät, vieraat ja näkemäsi hinta on tallennettu.",
    headline1: "Kotisi odottaa yhä sinua.",
    body1: (g, h) => `${g} tallensimme oleskelusi kohteessa ${h} juuri sellaisena kuin jätit sen: päivämäärät, vieraat ja hinnan. Yksi klikkaus ja jatkat siitä, tällä tai toisella laitteella.`,
    personal1: "Jos haluat tietää lisää talosta tai alueesta ennen päätöstä, vastaa tähän sähköpostiin. Luemme jokaisen vastauksen.",
    subject1Pay: (h) => `Varauksesi kohteeseen ${h} jäi kesken`,
    preheader1Pay: "Hintasi on voimassa. Viimeistele kortilla, Apple Paylla, Google Paylla, PayPalilla tai Klarnalla.",
    headline1Pay: "Tuliko jotain väliin?",
    body1Pay: (g, h) => `${g} pääsit jo maksuvaiheeseen oleskelullesi kohteessa ${h}, mutta varaus ei valmistunut. Näin käy monelle: hylätty kortti, pankin raja, viime hetken kysymys. Hintasi on edelleen voimassa ja voit maksaa haluamallasi tavalla: kortilla, Apple Paylla tai Google Paylla, PayPalilla tai osissa Klarnalla.`,
    personal1Pay: "Hoidatko asian mieluummin ihmisen kanssa? Vastaa tähän sähköpostiin tai kirjoita meille WhatsAppissa, niin viimeistelemme varauksen kanssasi.",
    subject2: (h, t) => `${h}: hintasi on voimassa klo ${t} asti`,
    preheader2: "Sen jälkeen päivämääriesi hinta lasketaan uudelleen.",
    headline2: "Hintasi on voimassa vielä muutaman tunnin.",
    body2: (g, h, u) => `${g} näkemäsi hinta kohteelle ${h} on taattu ${u} asti. Sen jälkeen laskemme hinnan uudelleen, ja päivämäärät ovat muiden vieraiden varattavissa, kunnes joku varaa ne.`,
    scarcity: (u, t) => `Päivämääriesi ympärillä olevista ${t} yöstä ${u} ei ole enää saatavilla.`,
    subject3: (h) => `Päivämääräsi kohteessa ${h} ovat yhä vapaina`,
    preheader3Gift: "Päivitimme hinnan, ja Flex on meidän tarjoamamme 72 tunnin ajan.",
    preheader3: "Tarkistimme saatavuuden uudelleen ja päivitimme hinnan.",
    headline3: "Päivämääräsi ovat yhä vapaina.",
    body3: (g, h) => `${g} tarkistimme kohteen ${h} uudelleen päivämäärillesi, ja ne ovat yhä vapaina. Päivitimme hinnan tämän päivän hintaan, alla.`,
    giftTitle: "Flex on meidän tarjoamamme",
    giftBody: (u, d, v) => `Varaa viimeistään ${u}, niin tarjoamme sinulle Flexin, joka maksaa normaalisti ${v}. Jos suunnitelmasi muuttuvat, voit siirtää oleskeluasi jopa ${d} päivää ennen saapumista menettämättä maksamaasi summaa.`,
    cta3Gift: "Varaa Flex mukaan lukien",
    cta3: "Katso tämän päivän hinta",
    flexIncluded: "Flex sisältyy",
    subject4: (h) => `Jos ${h} ei ole aivan oikea koti`,
    subject4None: () => "Autamme yhä mielellämme oleskelusi kanssa",
    preheader4: "Koteja samalla alueella, vapaina samoina päivinä.",
    headline4: "Ehkä oikea koti on toinen.",
    body4: (g, h) => `${g} et ole vielä varannut kohdetta ${h}, ja se on täysin ok: oikean kodin löytäminen vie aikaa. Valitsimme koteja samalta alueelta, vapaina päivinäsi, joista uskomme sinun pitävän.`,
    body4None: (g, h) => `${g} et ole vielä varannut kohdetta ${h}. Jos päivämäärät tai talo eivät aivan sovi, kerro mitä etsit, niin conciergemme löytää sinulle oikean vaihtoehdon.`,
    ownLink: (h) => `Takaisin kohteeseen ${h}`,
    lastNote: "Tämä on viimeinen sähköposti, jonka lähetämme tästä varauksesta.",
  },
};
